version: '3'

services:
  db:
    image: postgis/postgis:latest
    environment:
        POSTGRES_DB: meteorite-landings
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - custom-network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - custom-network 
    depends_on:
      - db
  
  app:
    build: .
    restart: on-failure
    environment:
        DATABASE_URL: postgresql+psycopg2://username:password@db:5432/meteorite-landings  
    volumes:
      - .:/app
    networks:
      - custom-network 
    depends_on:
      - db
    command: python main.py

networks:
  custom-network:
    driver: bridge